version: "3.8"

services:
  front:
    container_name: front
    build:
      context: .
      args:
        WORKDIR: $WORKDIR
    command: yarn run start
    volumes:
      - ".:/$WORKDIR"
    ports:
      - "$FRONT_PORT:3000"
    networks:
      - api_external
networks: 
  api_external:
    external: true