<template>
  <v-container
    class="mt-3"
  >
    <v-row>
      <v-col
        cols="3"
      >
        <v-sheet
          rounded="lg"
        >
          <v-list
            color="transparent"
          >
            <v-list-item>
              <v-list-item-content>
                <v-list-item-title>
                  マイページ
                </v-list-item-title>
              </v-list-item-content>
            </v-list-item>

            <v-divider/>

            <v-list-item
              :to="$my.userLinkToProfile(this.$auth.user.id)"
            >
              <v-list-item-avatar
                left
              >
                <v-icon>
                  mdi-account
                </v-icon>
              </v-list-item-avatar>
              <v-list-item-title>
                プロフィール
              </v-list-item-title>
            </v-list-item>
            <v-list-item
              :to="$my.userLinkToFollowing(this.$auth.user.id)"
            >
              <v-list-item-avatar
                left
              >
                <v-icon>
                  mdi-account-arrow-right
                </v-icon>
              </v-list-item-avatar>
              <v-list-item-title>
                フォロー
              </v-list-item-title>
            </v-list-item>
            <v-list-item
              :to="$my.userLinkToFollowed(this.$auth.user.id)"
            >
              <v-list-item-avatar
                left
              >
                <v-icon>
                  mdi-account-arrow-left
                </v-icon>
              </v-list-item-avatar>
              <v-list-item-title>
                フォロワー
              </v-list-item-title>
            </v-list-item>
            <v-list-item
              to="/mypage/address_payment"
            >
              <v-list-item-avatar
                left
              >
                <v-icon>
                  mdi-credit-card-marker-outline
                </v-icon>
              </v-list-item-avatar>
              <v-list-item-title>
                住所＆お支払い
              </v-list-item-title>
            </v-list-item>
          </v-list>
        </v-sheet>
      </v-col>
      <v-col
        cols="9"
      >
        <v-card
          flat
          rounded="lg"
        >
          <v-list
            color="transparent"
          >
            <v-list-item>
              <v-list-item-content>
                <v-list-item-title>
                  あなたの住所＆お支払い
                </v-list-item-title>
              </v-list-item-content>
            </v-list-item>

            <v-divider/>

            <v-list-item>
              <v-container>
                <v-row>
                  <v-col
                    cols="11"
                  >
                  <v-list>
                      <v-list-item>
                        <v-list-item-content>
                          <v-list-item-subtitle>
                            ※このページは他ユーザーには表示されません
                          </v-list-item-subtitle>
                        </v-list-item-content>
                      </v-list-item>
                    </v-list>
                    <v-list>
                      <v-list-item>
                        <v-list-item-content>
                          <v-list-item-title>
                            住所：{{ this.$store.state.user.login.zipcode }}
                            <br/><br/>
                            {{ this.$store.state.user.login.street }}
                            {{ this.$store.state.user.login.building }}
                          </v-list-item-title>
                        </v-list-item-content>
                      </v-list-item>
                    </v-list>
                    <v-list>
                      <v-list-item>
                        <v-list-item-content>
                          <v-list-item-title>
                            お支払い：クレジットカード
                            <br/><br/>
                            ＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊
                          </v-list-item-title>
                        </v-list-item-content>
                      </v-list-item>
                    </v-list>
                  </v-col>
                </v-row>
              </v-container>
            </v-list-item>
          </v-list>
        </v-card>
      </v-col>
    </v-row>
  </v-container>
</template>

<script>
export default {
  layout: 'mypage'
}
</script>