<template>
  <v-col
    cols="3"
  >
    <v-sheet
      rounded="lg"
    >
      <v-list
        color="transparent"
      >
        <v-list-item>
          <v-list-item-content>
            <v-list-item-title>
              マイページ
            </v-list-item-title>
          </v-list-item-content>
        </v-list-item>
        <v-divider/>
        <v-list-item
          :to="$my.userLinkToProfile(CurrentUser.id)"
        >
          <v-list-item-avatar
            left
          >
            <v-icon>
              mdi-account
            </v-icon>
          </v-list-item-avatar>
          <v-list-item-title>
            プロフィール
          </v-list-item-title>
        </v-list-item>
        <v-list-item
          :to="$my.userLinkToFollowing(CurrentUser.id)"
        >
          <v-list-item-avatar
            left
          >
            <v-icon>
              mdi-account-arrow-right
            </v-icon>
          </v-list-item-avatar>
          <v-list-item-title>
            フォロー
          </v-list-item-title>
        </v-list-item>
        <v-list-item
          :to="$my.userLinkToFollowed(CurrentUser.id)"
        >
          <v-list-item-avatar
            left
          >
            <v-icon>
              mdi-account-arrow-left
            </v-icon>
          </v-list-item-avatar>
          <v-list-item-title>
            フォロワー
          </v-list-item-title>
        </v-list-item>
        <v-list-item
          v-show="CurrentUser.id===$auth.user.id"
          to="/mypage/address_payment"
        >
          <v-list-item-avatar
            left
          >
            <v-icon>
              mdi-credit-card-marker-outline
            </v-icon>
          </v-list-item-avatar>
          <v-list-item-title>
            住所＆お支払い
          </v-list-item-title>
        </v-list-item>
      </v-list>
    </v-sheet>
  </v-col>
</template>

<script>
export default {
  layout: 'mypage',
  middleware: ['get-user-current'],
  computed: {
    CurrentUser() {
      const copyCurrentUser = this.$store.state.user.current
      return copyCurrentUser
    }
  }
}
</script>